DiazAdriel0/AUXIE-App

- Client/package-lock.json
- Client/package.json
Agregue las dependencias de react-redux y redux toolkit
> feat(Client): installed react-redux & toolkit

- Client/package-lock.json
- Client/package.json
- Client/src/main.tsx
- Client/src/redux/store.ts
cree el store sin actions o reducers, y agregue store y provider en main.tsx, falta crear slice, actions y reducers
> Lucabranch

- Client/src/App.tsx
- Client/src/views/form/auxieForm.tsx
- Client/src/views/form/clientForm.tsx
> Feat(forms)

- Client/src/App.tsx
- Client/src/views/form/auxieForm.tsx
- Client/src/views/form/clientForm.tsx
> added clientform route in app.tsx

- Client/src/components/card/card.tsx
- Client/src/components/cards/cards.tsx
Agregué los archivos para el componente card y el componente cards
> feat(client/components): added card and cards

- Server/Models/consumer.js
> defini el esquema/modelo de los consumidores

- Client/src/views/form/auxieform.module.scss
- Client/src/views/form/clientform.module.scss
aplique estilizado basico a los forms.
> estilizado basico

- Server/Models/provider.js
- Server/Routes/Routers/usersRouter.js
> Feat(server/provider model)  provider model created

- Client/src/App.jsx
- Client/src/views/Login/auxieLogin.jsx
- Client/src/views/Login/clientLogin.jsx
cree los archivos de login y setee las routes de cada login en la app.jsx
> created login files and set routes in app.jsx

- Server/Controllers/UserControllers/deleteConsumer.js
- Server/Controllers/UserControllers/deleteProvider.js
- Server/Handlers/UsersHandlers/deleteConsumerById.js
- Server/Handlers/UsersHandlers/deleteProviderById.js
estan separados los controller y handlers tanto para provider como para consumer, me falta escribir sus rutas
se usa borrado logico, por lo cual solo se hace el update de la propiedad isActive
> added controllers for delete and handlers

- Server/Controllers/UsersControllers/createProvider.js
- Server/Handlers/UsersHandlers/postPorovider.js
- Server/Models/provider.js
- Server/Routes/Routers/consumersRouter.js
- Server/Routes/Routers/providersRouter.js
- Server/Routes/Routers/usersRouter.js
- Server/Routes/mainRouter.js
División de userRouter en provider y consumer
Creación de handler y controller
> Feat(server/routes)  add /post providers

- Server/Controllers/ServicesControllers/getAllServices.js
- Server/Handlers/ServicesHandlers/handlerServices.js
También traje "name" y "category" por query
> Cree el handler y controllers de los Servicios

- Server/App/app.js
- Server/Handlers/ProvidersHandlers/postPorovider.js
- Server/Routes/mainRouter.js
Hice la conexión en App.js del server con las rutas y modifique la importacion de consumersRouter en mainRouter
> Connection server with routes

- Server/Controllers/ConsumersControllers/createConsumer.js
- Server/Handlers/ConsumersHandlers/postConsumer.js
> Feat(server/handler controller)post consumer

- Server/Controllers/ConsumersControllers/loginC.js
- Server/Controllers/ProvidersControllers/loginP.js
- Server/Handlers/ConsumersHandlers/loginConsumer.js
- Server/Handlers/ProvidersHandlers/loginProvider.js
- Server/package-lock.json
- Server/package.json
> added login handler/controllers- and i bcrypt

- Server/Handlers/ProvidersHandlers/postPorovider.js
- Server/Models/provider.js
Agregué la propiedad image al modelo provider y hashee la password antes de guardarla en la DB
> image property added, password hashed

- Server/Controllers/ProvidersControllers/getAllProviders.js
- Server/Handlers/ProvidersHandlers/getProviders.js
arregle un error el el controller para que arroje un false y en el handler maneje si true o false para dar la respuesta
> fixed catch getAllProvider

- Client/src/utils/validationutils.js
- Client/src/views/Login/auxieLogin.jsx
- Client/src/views/Login/auxieLogin.module.scss
- Client/src/views/Login/clientLogin.jsx
- Client/src/views/Login/clientLogin.module.scss
- Client/src/views/form/auxieForm.jsx
- Client/src/views/form/auxieform.module.scss
- Client/src/views/form/clientForm.jsx
- Client/src/views/form/clientform.module.scss
logins y forms con estilo basico. Validaciones de inputs. agregue buttondisabled. validaciones en su propio archivo dentro de utils.
> Update(client/login&form) validations

- Server/Models/provider.js
Agregué el transform al modelo providers
> transform _id to id

- Server/Models/provider.js
arreglé el transform del modelo provider
> transform fixed

- Server/Controllers/ProvidersControllers/findProviderById.js
- Server/Handlers/ProvidersHandlers/getProviderById.js
- Server/Routes/Routers/providersRouter.js
Agregué la ruta GET de provider para obtener por id con su handler y controller
> provider by id handler and controller added

- Server/Handlers/ServicesHandlers/handlerPostService.js
- Server/Routes/Routers/servicesRouter.js
> Cree las rutas del Service

- Server/Controllers/ConsumersControllers/findAllConsumers.js
- Server/Controllers/ProvidersControllers/getAllProviders.js
- Server/Handlers/ConsumersHandlers/getAllConsumers.js
- Server/Handlers/ProvidersHandlers/getProviders.js
- Server/Routes/Routers/consumersRouter.js
Creé handler y controller para obtener todos los usuarios de la base de datos
> get all consumers route create

- Client/src/utils/validationutils.js
- Client/src/views/aboutUs/AboutUs.jsx
- Client/src/views/aboutUs/aboutUs.module.scss
> Feat(client/about us)

- Server/Routes/mainRouter.js
> pureba apdd

- Server/Controllers/ConsumersControllers/matchConsumer.js
Arreglé el error en la respuesta cuando el email no coincidía con ningún usuario
> Fix response error when email does not match

- .env
- Client/package-lock.json
- Client/package.json
- Client/src/components/Filters/Filters.jsx
- Client/src/redux/rootReducer.js
- Client/src/views/home/Home.jsx
Agregué React Select (recuerden hacer "npm i"), y adapte la logica de los filtros de forma acorde
> Feat(client/filters) added react select and adapted filters

- Server/Controllers/ProvidersControllers/findAndUpdateProvider.js
- Server/Handlers/ProvidersHandlers/updateProvider.js
- Server/Routes/Routers/providersRouter.js
Creación de handler y controller para la actualización de datos del perfil de un provider
> Feat(server/provider)  add /put provider handler and controller

- Client/src/App.jsx
- Client/src/components/card/card.jsx
- Client/src/components/cards/cards.jsx
- Client/src/redux/Actions/actions.js
- Client/src/redux/rootReducer.js
- Client/src/views/detail/Detail.jsx
agregué un Link a las cards para que las redireccione a su componente detail
> feat(client/detail) added card redirect to detail

- Client/src/views/aboutUs/AboutUs.jsx
- Client/src/views/aboutUs/aboutUs.module.scss
> Update(client/about us)

- Server/Models/request.js
ahi cree el modelo para las peticiones
> created request's model

- Client/src/components/Filters/Filters.jsx
- Client/src/redux/Actions/actions.js
- Client/src/redux/rootReducer.js
Arregle el filtrado por tipo de servicio
> fix(client/redux) fixed filters

- Server/Controllers/ConsumersControllers/addFavProviders.js
- Server/Handlers/ConsumersHandlers/favoriteProviders.js
- Server/Routes/Routers/consumersRouter.js
agregue la posibilidad de marcar favoritos
lo que se modifica es un array de obj y pusheo un prov a los favs del consumer
> Feat(server/handler controller) add favorite provider

- Server/Controllers/ProvidersControllers/modifyProviderReviews.js
- Server/Handlers/ProvidersHandlers/updateProviderReviews.js
- Server/Routes/Routers/providersRouter.js
Creé la ruta put para asignar reviews de un consumer a un provider con su handler y controller
> Feat(server/provider)  add /put to assing review

- Server/Controllers/ConsumersControllers/deleteFavProvider.js
- Server/Handlers/ConsumersHandlers/deleteFavoriteProv.js
- Server/Routes/Routers/consumersRouter.js
cree el handler-controller y routa para borrar u fav Provider del consumer
si la ruta es delete/fav es xq me estaba dando error del put /fav 
al intentar ser delete/fav
> Feat(server/handler controller) add delete favorite provider

- Client/src/components/nav-landing/NavLanding.jsx
- Client/src/views/landingViews/aboutUs/AboutUs.jsx
- Client/src/views/landingViews/aboutUs/aboutUs.module.scss
> about us completado

- Server/Handlers/ProvidersHandlers/updateProviderReviews.js
Arreglé lo del return que devolvía el objeto
> return message fixed

- Server/Controllers/ProvidersControllers/modifyProviderServices.js
- Server/Handlers/ProvidersHandlers/updateOfferedServices.js
Además de lo que hacía, agregué que se pushee el username del provider a la propiedad providers de la coleccion services
> In addition, now adds providers to the services

- Client/src/views/Home/home-consumer/HomeConsumer.jsx
- Client/src/views/Home/home-consumer/homeConsumer.module.scss
agregue los cambios que le habia hecho a mi home antes de que joshua moviera todas las carpetas de lugar
> feat(client) added home changes

- Server/Controllers/ProvidersControllers/addPendingService.js
Ahora si pude probar y tenía un pequeño error
> Error fixed

- Client/src/components/nav-landing/NavLanding.jsx
Agregué un redirect hacia landing cuando clickeas el logo
> feat(client/nav-landing) logo redirects to landing

- Client/src/views/detail/Detail.jsx
- Client/src/views/detail/detail.module.scss
Agregué estilo a la view de detail de auxie
> feat(client/detail) added style to detail page

- Client/src/utils/validationutils.js
- Client/src/views/forms/auxie-form/auxieForm.jsx
- Client/src/views/forms/auxie-form/auxieform.module.scss
- Client/src/views/forms/client-form/ClientForm.jsx
- Client/src/views/forms/client-form/clientform.module.scss
Tiene select para genero. Validacion que tenga seleccionado uno y boton deshabilitado si no tiene seleccionado un genero.
> Hotfix(client/forms) update para gender

- Client/src/views/landingViews/aboutUs/AboutUs.jsx
- Client/src/views/landingViews/aboutUs/aboutUs.module.scss
actualice las cards para poder dar click en los github atras. modifique el frente un poco
> Updated About us. links atras, funcan

- Client/src/views/landingViews/aboutUs/AboutUs.jsx
- Client/src/views/landingViews/aboutUs/aboutUs.module.scss
> Update(client/aboutus) titulos a about cards

- Client/src/views/forms/auxie-form/auxieForm.jsx
- Client/src/views/forms/client-form/ClientForm.jsx
- Client/src/views/forms/client-form/clientform.module.scss
> Update(login) detallitos funcionales

- Server/Controllers/ProvidersControllers/matchProvider.js
faltaba arreglar cuando se logeaba con email
> fix login return

- Server/Handlers/ProvidersHandlers/updateProvider.js
- Server/Models/provider.js
Agregué la propiedad bio a los proviuders
> bio added to provider

- Server/Handlers/ProvidersHandlers/postPorovider.js
- Server/Handlers/ProvidersHandlers/updateProvider.js
Agregué el '?' para que no se rompa si no vienen esos datos por body
> Optional chaining added

- Client/src/components/nav-general/NavGeneral.jsx
- Client/src/components/nav-general/navGeneral.module.scss
- Client/src/redux/rootReducer.js
- Client/src/views/Home/home-consumer/HomeConsumer.jsx
- Client/src/views/detail/Detail.jsx
> feat(client/navgeneral) added nav general

- Client/src/components/card/card.jsx
- Client/src/components/cards/cards.jsx
las cards de los auxies tienen foto de perfil personalizada
> fix(client/card) added custom profile pic

- Server/Controllers/ProvidersControllers/addJob.js
- Server/Handlers/ProvidersHandlers/postPorovider.js
Default image added to provider
Default requestDate added to jobs
jobDate property added to jobs
> Properties added to provider

- Client/src/components/card-services/CardServices.jsx
- Client/src/components/cards-services/CardsServices.jsx
Agregué imágenes a las cards de services
REVISAR ANTES DE APROBAR porque se rompe el estilo
> image added to cards of services

- Client/src/views/landing/Landing.jsx
El select que está en la portada de la landing, en la solapa convertirme en auxie no mostraba ningun servicio al desplegar
> select of services fixed

- Client/src/views/landing/Landing.jsx
Agregué la redireccion de los botones a los formularios de registro
> buttons redirect to register

- Client/src/views/landingViews/help/Help.jsx
Agregué la funcionalidad de los botones ingresar y registrarse pero no les dí estilos, habría que ver de hacer un componente reutilizable para mostrar en todas las vistas
> buttons login and register

- Client/src/components/loginRegisterMenus/LoginRegistermenus.jsx
- Client/src/components/loginRegisterMenus/loginRegisterMenus.module.scss
- Client/src/components/nav-landing/NavLanding.jsx
- Client/src/views/landingViews/aboutUs/AboutUs.jsx
- Client/src/views/landingViews/guarantee/Guarantee.jsx
- Client/src/views/landingViews/help/Help.jsx
- Client/src/views/landingViews/howItWorks/HowItWorks.jsx
- Client/src/views/landingViews/offer/Offer.jsx
Creé el componente reutilizable para la nav que tiene los botones ingresar y registrarse.
> reusable component created and applied in views

- Client/src/views/Home/home-consumer/HomeConsumer.jsx
Una prueba de como podria ser la logica del redirect (si tienen una forma de redireccionar que creen mejor avisen)
> feat(client/homeconsumer) added redirect

- Client/src/views/landing/landing.module.scss
> footer change color

- Client/src/components/loginRegisterMenus/LoginRegistermenus.jsx
- Client/src/components/loginRegisterMenus/loginRegisterMenus.module.scss
- Client/src/sass/abstracts/_variables.scss
> loginRegisterMenus styled

- Client/src/views/Home/home-consumer/HomeConsumer.jsx
ignoren el nombre de la branch
> saludo personalizado

- Client/src/views/Home/home-auxie/HomeAuxie.jsx
- Client/src/views/landing/Landing.jsx
Imagen de la nav (no mostraba foto de perfil)
Agregué imagenes a todos los servicios, y arreglé el error de que no se mostraban imagenes en las cards en la vista homeAuxie
> image added to cards in homeAuxie view

- Client/src/components/card/card.jsx
- Client/src/views/Home/home-auxie/HomeAuxie.jsx
- Client/src/views/Home/home-auxie/homeAuxie.module.scss
- Client/src/views/home-views/auxie-views/auxie-inbox/AuxieInbox.jsx
- Client/src/views/home-views/auxie-views/auxie-inbox/auxieInbox.module.scss
- Client/src/views/home-views/auxie-views/auxie-statistics/AuxieStatistics.jsx
- Client/src/views/home-views/auxie-views/auxie-statistics/auxieStatistics.module.scss
> Feat(client/home auxie)  fix panels

- Client/src/views/Home/home-consumer/HomeConsumer.jsx
- Client/src/views/Home/home-consumer/homeConsumer.module.scss
Le robe el footer a la landing y le agregué links de redireccionado a las views que tiene el navbar landing
> feat(client/homeconsumer) added footer

- Client/package-lock.json
- Client/package.json
- Client/src/components/nav-general/NavGeneral.jsx
- Client/src/components/nav-general/navGeneral.module.scss
Agregué un popup en el boton de usuario con opciones
> feat(client/navgeneral) added popup options

- Client/src/views/forms/auxie-form/auxieForm.jsx
- Client/src/views/forms/client-form/ClientForm.jsx
ahi configure el form de registro para que tenga toen y se comunique con firebase
> register with auth

- Client/src/components/card-services/cardServices.module.scss
- Client/src/components/card/card.module.scss
- Client/src/components/nav-general/navGeneral.module.scss
- Client/src/sass/abstracts/_variables.scss
- Client/src/views/detail/detail.module.scss
- Client/src/views/forms/support-form/SupportForm.module.scss
- Client/src/views/landing/landing.module.scss
- Client/src/views/landingViews/guarantee/guarantee.module.scss
- Client/src/views/landingViews/howItWorks/howItWorks.module.scss
- Client/src/views/landingViews/offer/offer.module.scss
Actualice las variables con nombres correspondientes, reemplace las variables con su nombre nuevo donde fueron usadas.
> Update(client/sass) variables

- Client/src/views/Home/home-auxie/HomeAuxie.jsx
- Server/Handlers/ServicesHandlers/handlerPutService.js
- Server/Models/service.js
- Server/Routes/Routers/servicesRouter.js
Cloudinary terminado, todas las fotos (perfil de usuarios y servicios) ya están en la base de datos de cloudinary.
> Feat(server/app)  cloudinary implementation

- Client/src/components/nav-general/NavGeneral.jsx
luca mergeaste muy rapido no me dejaste resolver el conflicto xD
> hotfix(client/navgeneral)

- Client/src/views/forms/client-form/ClientForm.jsx
- Server/Handlers/ConsumersHandlers/welcomeEmail.js
- Server/Routes/Routers/consumersRouter.js
- Server/Utils/nodemailer.js
- Server/package-lock.json
- Server/package.json
agregué nodemailer y email de bienvenida
> feat(server/consumers) nodemailer welcome email

- Client/src/views/forms/client-form/ClientForm.jsx
> modularizado para que mili no me pegue

- Client/src/components/card/card.jsx
el botoncito de fav ahora esta bonito
> Botoncito fav bonito

- Server/Controllers/ProvidersControllers/addJob.js
- Server/Handlers/ProvidersHandlers/updateJobs.js
Agregué una notificación por mail para el auxie cuando un usuario solicita un servicio de él
> Feat(server/update jobs)  mail added to update jobs

- Server/Handlers/ClaimsHandlers/handlerPostClaim.js
- Server/Utils/cloudinary.js
Agregué un achivo de imagen que se suba a cloudinary a la ruta POST claims
> image file added to claims

- Client/src/components/featuredAuxies/FeaturedAuxies.jsx
- Client/src/components/featuredAuxies/featuredAuxies.module.scss
- Client/src/components/featuredAuxies/featuredCard/FeaturedCard.jsx
- Client/src/components/featuredAuxies/featuredCard/featuredCard.module.scss
- Client/src/utils/shuffle.js
- Client/src/views/landing/Landing.jsx
- Client/src/views/landing/landing.module.scss
agregué unos featured auxies al landing (hay conflicto con el renderizado, se re-renderiza constantemente cuando scrolleas)
> feat(client(landing) featured auxies

- Server/Handlers/ConsumersHandlers/postConsumer.js
- Server/Handlers/ProvidersHandlers/updateJobs.js
Agregué el nuevo formato de nodemailer a todos los handlers donde estaba el formato anterior
> new nodemailer added to updateJobs and postConsumer

- Client/package-lock.json
- Client/package.json
- Client/src/views/detail/Detail.jsx
- Client/src/views/detail/detail.module.scss
Agregué libreria de carousel. Todos los auxies tienen las mismas imagenes, hay que agregar propiedad con imagenes de trabajos terminados al modelo providers.
> Added carousel to Detail view

- Client/src/components/card/card.module.scss
- Client/src/components/featuredAuxies/FeaturedAuxies.jsx
- Client/src/views/chat/App.jsx
- Client/src/views/chat/Chat.jsx
- Client/src/views/forms/jobRequest-Form/JobRequestForm.jsx
- Client/src/views/landing/Landing.jsx
Las cards features ya no son aleatorias con cada render.
Las cards auxie del home consumer tienen boton con estilo acorde a landing
> Fix featured random render

- Client/src/components/cards-services/CardsServices.jsx
- Client/src/views/profile/profileAuxies/ProfileAuxies.jsx
- Client/src/views/profile/profileConsumers/ProfileConsumers.jsx
funcion de redirigir en el boton de cambiar contraseña
> added navigate to reset password on click

- Client/src/views/forms/auxie-form/AuxieForm.jsx
- Client/src/views/forms/client-form/ClientForm.jsx
muestra un sweet alert cuando el correo ya esta registrado
> Feat(front/register) alert error

- Server/Handlers/ServicesHandlers/handlerPostService.js
Agregué foto default a los servicios agregados si no se envía imagen
> default image added

- Server/Handlers/ServicesHandlers/handlerPostService.js
- Server/Models/provider.js
Agregué gallery al modelo provider
> Feat(server/provider model)  gallery added to model

- Client/src/views/forms/jobRequest-Form/JobRequestForm.jsx
- Server/Controllers/ProvidersControllers/addJob.js
Agregué en el formulario de contrato el select de método de pago y en cada objeto job del array jobs del provider va a agregarse el metodo de pago a partir de ahora
> payment method added to jobs

- Server/Controllers/ProvidersControllers/updateGallery.js
- Server/Handlers/ProvidersHandlers/updateProvider.js
- Server/Utils/cloudinary.js
Agregué la galería de imagenes al modelo y en el handler se puede recibir un array de imagenes que se suben cloudinary
> Gallery added to provider model and upload of images

- Client/src/views/profile/profileAuxies/ProfileAuxies.jsx
- Server/Controllers/ProvidersControllers/updateGallery.js
- Server/Handlers/ProvidersHandlers/updateProvider.js
> fixed update gallery

- Client/src/components/nav-general/NavGeneral.jsx
- Client/src/components/nav-general/navGeneral.module.scss
- Client/src/components/profile-pic/profile-pic-auxie/ProfilePic.jsx
- Client/src/views/forms/auxie-form/AuxieForm.jsx
- Client/src/views/forms/client-form/ClientForm.jsx
- Client/src/views/login/auxie-login/AuxieLogin.jsx
- Client/src/views/login/consumer-login/ClientLogin.jsx
- Client/src/views/profile/profileAuxies/ProfileAuxies.jsx
- Client/src/views/profile/profileAuxies/ProfileAuxies.module.scss
- Client/src/views/profile/profileConsumers/ProfileConsumers.jsx
- Client/src/views/profile/profileConsumers/ProfileConsumers.module.scss
- Client/src/views/profile/profilePage/ProfilePage.jsx
Agregué un navbar a cada view, para que los formularios y el perfil no queden en una vista sin forma de navegar.
Ademas arreglé un bug que hacia que al desconectarte como auxie se rompa la pagina y no te retorne a landing
> Todas las views con navbar

- Server/Controllers/ProvidersControllers/addJob.js
Error que no sumaba id sino concatenaba resuelto
> solved problem with id

- Client/src/components/home-auxie-components/table-services/TableServices.jsx
- Client/src/components/home-auxie-components/table-services/tableServices.module.scss
- Client/src/views/forms/price-form/PriceForm.jsx
- Client/src/views/forms/price-form/priceForm.module.scss
Creación del botón "Propuesta" que muestra el form en la homeauxie y se deja de mostrar cuando se hace click fuera del form
> Form to change price created

- Client/src/components/home-auxie-components/table-services/TableServices.jsx
- Client/src/components/home-auxie-components/table-services/tableServices.module.scss
- Client/src/views/forms/price-form/PriceForm.jsx
- Client/src/views/forms/price-form/priceForm.module.scss
- Server/Controllers/ProvidersControllers/addJob.js
> finished form structure

- Server/.gitignore
> gitignore updated

- Client/src/components/pagination/usePagination.js
Tiraba error al desloguearse por no encontrar data en usePagination
> fixed error white screen on logout

- Client/src/components/favoriteAuxieCard/FavoriteAuxieCard.jsx
- Client/src/components/favoriteAuxieCard/favoriteAuxieCard.module.scss
- Client/src/components/favoriteAuxiesCards/FavoriteAuxiesCards.jsx
- Client/src/components/favoriteAuxiesCards/favoriteAuxiesCards.module.scss
- Client/src/views/profile/profileConsumers/ProfileConsumers.jsx
- Client/src/views/profile/profileConsumers/ProfileConsumers.module.scss
Dividí el perfil en información personal de la cuenta, y contenido que tiene que ver con auxies y servicios.
Agregué sección con favoritos
> Perfil dividido

- Client/src/App.jsx
- Client/src/components/clientRequiredServices/ClientRequiredServices.jsx
- Client/src/components/clientRequiredServices/clientRequiredServices.module.scss
- Client/src/components/profile-pic/profile-pic-auxie/ProfilePic.jsx
- Client/src/views/requestedServices/RequestedServices.jsx
- Client/src/views/requestedServices/requestedServices.module.scss
El popup de la navbar del cliente ahora tiene un botón que te redirecciona a la view de los servicios requeridos.
> view de servicios requeridos como cliente

- Client/src/views/forms/price-form/PriceForm.jsx
El botón propuesta tiraba error cuando el servicio estaba hardcodeado y le faltaban propiedades
> fixed error when service is empty

- Client/src/views/chat/Chat.jsx
- Client/src/views/detail/Detail.jsx
Envio de notificacion cuando se envía un mensaje por chat
> Feat(client/notifications)  sending notifications

- Client/src/components/home-auxie-components/table-services/TableServices.jsx
- Server/Controllers/ProvidersControllers/addJob.js
- Server/Controllers/ProvidersControllers/modifyJobStatus.js
- Server/Handlers/ProvidersHandlers/updateJobStatus.js
si eventualmente llega el push, nice
son las notificaciones para el consumer que hice ayer
> accept o decline notif for the consumer

- Client/src/components/card/Card.jsx
- Client/src/components/cards/Cards.jsx
se les notifica a los auxies que alguien los añadio a sus favoritos
> fav added notif for auxies

- Server/Controllers/ProvidersControllers/addJob.js
- Server/Models/request.js
El job se agrega al array requiredServices del consumer y se crea un documento en la colección request
> requiredServices and jobs updated

- Client/src/components/home-auxie-components/aside-auxie/asideAuxie.module.scss
- Client/src/components/nav-landing/navLanding.module.scss
> start-flexstart

- Client/src/components/home-auxie-components/table-services/TableServices.jsx
- Server/Models/request.js
le envia notificaciones al consumer cuando el trabajo se termina o cuando se cancela
> added notif on service done or cancelled by auxie

- Client/src/views/landingViews/howItWorks/howItWorks.module.scss
en teoria es un semi-casi-neeeh responsive hasta 800px x lo menos
> Fix(css)little fix on responsive

- Client/src/views/forms/client-form/ClientForm.jsx
- Client/src/views/forms/jobRequest-Form/JobRequestForm.jsx
Agregué el circulo de carga cuando se presiona el boton enviar en la vista donde se contrata al auxie
> loader added to jobRequestForm

- Client/src/views/landingViews/aboutUs/AboutUs.jsx
- Client/src/views/landingViews/aboutUs/aboutUs.module.scss
le añadi el padding a nuestras cards para que se separen un poco del footer
cambie un poco los tamaños y añadi algo de weight o quite, para que se notara la jerarquia, tambien añadi los signos de rpegunta faltantes
> added padding and weight to some fonts

- Client/src/views/landingViews/aboutUs/AboutUs.jsx
- Client/src/views/landingViews/aboutUs/aboutUs.module.scss
- Client/src/views/landingViews/howItWorks/howItWorks.module.scss
hice un par de  cambios y puse la flecha de faqs al costado
pero avisenme si rompe
> Little fix(how it works)

- Client/src/views/landing/Landing.jsx
- Client/src/views/landing/landing.module.scss
agregué algunas tildes, 
le puse un poco de espacio entre nuestros servicios(title) y las cards
cambie un poco el weight de las fonts en el slogan
> fixed gap between title and cards, changed tildes

- Server/Models/request.js
simplemente le añadi las propiedades xq en addJob yo le doy clientUid
pero si no existe en el modelo, me arruina las notificaciones
del mismo modo ProviderUid la añadi por si despues nos damos cuenta q es necesaria
> addedProperty

- Client/src/components/clientRequiredService/ClientRequiredService.jsx
- Client/src/components/clientRequiredService/clientRequiredService.module.scss
- Client/src/components/clientRequiredServices/clientRequiredServices.module.scss
Las cards de required services ahora son horizontales estilo mercado libre
> Client required services horizontal cards

- Client/src/views/chat/Chat.jsx
- Client/src/views/chat/chat.module.scss
- Client/src/views/detail/Detail.jsx
- Client/src/views/detail/detail.module.scss
le añadi el boton de minimizar al chat
y scrollea al bottom de la conversacion
algo de font weight
> added minimize chat, sroll to the bottom

- Client/src/views/landingViews/offer/Offer.jsx
- Client/src/views/landingViews/offer/offer.module.scss
cambie un poco la organizacion de offer para que sea un poco más sencillo el responsive
> changed offer (consultar)

- Client/src/components/buttonMercadoPago/ButtonMercadoPago.jsx
- Client/src/components/clientRequiredServices/ClientRequiredServices.jsx
Agregué el circulo de carga al boton de MercadoPago
> loader added to button

- Client/src/components/chatcomponents/chatlist.jsx
- Client/src/components/chatcomponents/chatlist.module.scss
- Client/src/views/chat/chat.module.scss
- Client/src/views/detail/detail.module.scss
le añadi el botom de minimize a chatInbox de auxie y corregi que le faltaba una llave  aotro estilo
> added minimize button at chatInbox

- Client/src/components/clientRequiredService/ClientRequiredService.jsx
- Client/src/components/clientRequiredService/clientRequiredService.module.scss
te cambie un poquito la card patoooo
> little changes

- Server/Controllers/ProvidersControllers/addJob.js
Arreglé la fecha y la hora que se guarda en el array jobs
> jobDate fixed

- Client/src/components/clientRequiredService/ClientRequiredService.jsx
formateo la fecha para qu esea una fecha coherente
> formato date

- Client/src/App.jsx
- Client/src/components/buttonMercadoPago/ButtonMercadoPago.jsx
- Client/src/components/clientRequiredService/ClientRequiredService.jsx
- Client/src/components/notifications/Notifications.jsx
- Client/src/components/payment/PaymentSuccess.jsx
- Server/Controllers/ProvidersControllers/findProvUid.js
- Server/Handlers/MercadoPagoHandlers/handlerMercadoPago.js
- Server/Handlers/ProvidersHandlers/getProvUid.js
- Server/Routes/Routers/providersRouter.js
añadi redireccionamiento de mp, cree rutas y evita que cualquiera pueda entrar x url
> Mp redirect

- Client/src/components/landing-do-not-enter/LoginRegister.jsx
- Client/src/components/loginauxie/LoginRegister.jsx
- Server/Controllers/ConsumersControllers/matchConsumer.js
- Server/Controllers/ProvidersControllers/getAllProviders.js
- Server/Models/consumer.js
> Added(is active)

- Client/src/components/clientRequiredService/ClientRequiredService.jsx
- Client/src/components/clientRequiredServices/ClientRequiredServices.jsx
- Client/src/views/forms/review-form/ReviewForm.jsx
- Client/src/views/forms/review-form/reviewform.module.scss
- Client/src/views/profile/new-profile-consumers/NewProfileConsumers.jsx
- Server/Controllers/ProvidersControllers/modifyProviderReviews.js
Arreglé el formulario de reviews
> reviewForm fixed
